# This is a basic workflow to help you get started with Actions

name: ro0t!

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets._x }}
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
        path: ${{ secrets._x_path }}
      
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "ro0t!" -Force)

    - name: Setup ngrok
      shell: pwsh
      run: |
        powershell -File $env:X_PATH\scripts\windows\ngrok_setup.ps1 $env:NGROK_AUTH_TOKEN $env:X_PATH
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\tools\bin\ngrok\windows\ngrok.exe" start --all"'
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        X_PATH: ${{ secrets._x_path }}

    - name: Finish
      run: |
        cmd /c .\$env:X_PATH\scripts\windows\start.bat
        powershell -File $env:X_PATH\scripts\windows\timeout.ps1
      env:
        X_PATH: ${{ secrets._x_path }}
