name: ro0t!

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      X_PATH: ${{ secrets._x_path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets._x }}
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: ${{ secrets._x_path }}
      
      - name: Enable TS
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "ro0t!" -Force)

      - name: Setup ngrok
        shell: pwsh
        run: |
          & $env:X_PATH\scripts\windows\ngrok_setup.ps1 $env:NGROK_AUTH_TOKEN $env:X_PATH
          Start-Process Powershell -ArgumentList '-Noexit -Command ".\tools\bin\ngrok\windows\ngrok.exe" start --all"'

      - name: Finish
        shell: pwsh
        run: |
          & $env:X_PATH\scripts\windows\start.ps1
          & $env:X_PATH\scripts\windows\connect.ps1 $env:NGROK_API_TOKEN
          & $env:X_PATH\scripts\windows\timeout.ps1